name: ravengate_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sign_in_button: ^3.2.0
  local_auth: ^2.2.0
  google_sign_in: ^6.1.6
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

# Configuración del icono de la aplicación
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ravengateIconBlack.png"
  adaptive_icon_background: "#FFFFFF" # Fondo blanco
  adaptive_icon_foreground: "assets/images/ravengateBlackIconPaddedpng.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21

# Configuración de la splash screen
flutter_native_splash:
  # Color de fondo para el modo claro
  color: "#FFFFFF"
  # Imagen que se mostrará en el centro
  image: assets/images/ravengateBlackIconPaddedpng.png

  # Configuración para modo oscuro (opcional)
  color_dark: "#121212"
  image_dark: assets/images/icon_foreground_padded.png

  # Configuración específica para Android 12+
  android_12:
    image: assets/images/ravengateBlackIconPaddedpng.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/icon_foreground_padded.png
    icon_background_color_dark: "#121212"

  # Configuraciones adicionales
  fullscreen: true # Para ocultar la barra de estado durante la splash screen
  android: true
  ios: true
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
